### ISSUE TITLE
Instalar o login cidadao

### ISSUE THREAD

**Issue by uira** [Mutirao/RedeCultura#1]

**Comment by jacsonp** [comment]
login na raiz da redelivre funcionando, faltando colocar os sites que vão usar o serviço na url de retorno que o id.org.br vai responder, precisa falar com o donato ou desenvolver e fazer um pull request para modificar a validação da url permitindo IP (redirect url é 10.0.0.1/oauth é valido para exemplo.com pois resolve para 10.0.0.1 no momento do login) e wildcard (aceitando *.redelivre.org.br/oauth)

**Comment by guilhermednt** [comment]
A lib de OpenID Connect permite configurar como será o matching da `redirect_uri`. A lib tem um parâmetro `require_exact_redirect_uri` que pode ser definido como `false`. Teria que testar se isso atende o que vocês precisam.

Para alterar essa configuração temos as seguintes formas:

1. Versionando essa configuração:
1.1. No `app/config/config.yml` basta incluir o parâmetro `oauth2.server.config.require_exact_redirect_uri: false`. Exemplo:
``` yaml
# app/config/config.yml
parameters:
    oauth2.server.config.require_exact_redirect_uri: false
    # ... outros parâmetros que já estão definidos
```

2. Não versionando através do parameters.yml:
2.1. Adicionar `oauth2.server.config.require_exact_redirect_uri: false` em `parameters.yml`, `parameters.yml.dist` e `parameters.yml.vagrant`

Dessa forma o valor do parâmetro não ficará versionado (embora os arquivos .dist e .vagrant possuam sugestões de valores default).

3. Caso a instância do LC possua um bundle de customizações, também é possível definir os parâmetros de forma análoga a opção **1**, por exemplo no arquivo `<SeuBundle>/Resources/config/services.yml`

* _Caso essa feature da lib não atenda a necessidade, a mudança deve ser feita na [própria lib](https://github.com/bshaffer/oauth2-server-php/blob/master/src/OAuth2/Controller/AuthorizeController.php#L401), não no Login Cidadão..._
